import random
import json

destinations = [
    ("Goa", "India", "beach"),
    ("Manali", "India", "mountain"),
    ("Shimla", "India", "mountain"),
    ("Leh", "India", "mountain"),
    ("Srinagar", "India", "mountain"),
    ("Munnar", "India", "mountain"),
    ("Ooty", "India", "mountain"),
    ("Darjeeling", "India", "mountain"),
    ("Jaipur", "India", "city"),
    ("Udaipur", "India", "city"),
    ("Mumbai", "India", "city"),
    ("Delhi", "India", "city"),
    ("Bangalore", "India", "city"),
    ("Kolkata", "India", "city"),
    ("Chennai", "India", "city"),
    ("Kerala", "India", "beach"),
    ("Andaman", "India", "beach"),
    ("Pondicherry", "India", "beach"),
    ("Bali", "Indonesia", "beach"),
    ("Phuket", "Thailand", "beach"),
    ("Krabi", "Thailand", "beach"),
    ("Maldives", "Maldives", "beach"),
    ("Santorini", "Greece", "beach"),
    ("Mykonos", "Greece", "beach"),
    ("Dubai", "UAE", "city"),
    ("Abu Dhabi", "UAE", "city"),
    ("Singapore", "Singapore", "city"),
    ("Tokyo", "Japan", "city"),
    ("Kyoto", "Japan", "city"),
    ("Osaka", "Japan", "city"),
    ("Seoul", "South Korea", "city"),
    ("Bangkok", "Thailand", "city"),
    ("Paris", "France", "city"),
    ("London", "United Kingdom", "city"),
    ("Rome", "Italy", "city"),
    ("Venice", "Italy", "city"),
    ("Barcelona", "Spain", "city"),
    ("Madrid", "Spain", "city"),
    ("Amsterdam", "Netherlands", "city"),
    ("Prague", "Czech Republic", "city"),
    ("Vienna", "Austria", "city"),
    ("Zurich", "Switzerland", "mountain"),
    ("Interlaken", "Switzerland", "mountain"),
    ("Lucerne", "Switzerland", "mountain"),
    ("New York", "USA", "city"),
    ("Los Angeles", "USA", "city"),
    ("San Francisco", "USA", "city"),
    ("Las Vegas", "USA", "city"),
    ("Miami", "USA", "beach"),
    ("Honolulu", "USA", "beach"),
    ("Sydney", "Australia", "beach"),
    ("Melbourne", "Australia", "city"),
    ("Queenstown", "New Zealand", "mountain"),
    ("Auckland", "New Zealand", "city"),
    ("Cape Town", "South Africa", "beach"),
    ("Marrakech", "Morocco", "city"),
    ("Istanbul", "Turkey", "city"),
    ("Cairo", "Egypt", "city"),
    ("Petra", "Jordan", "adventure"),
    ("Machu Picchu", "Peru", "adventure")
]

activities_pool = [
    "water sports",
    "snorkeling",
    "scuba diving",
    "surfing",
    "jet skiing",
    "parasailing",
    "banana boat rides",
    "yacht cruises",
    "sunset cruises",
    "nightlife",
    "beach hopping",
    "island hopping",
    "shopping",
    "luxury shopping",
    "street food tours",
    "local cuisine tours",
    "wine tasting",
    "coffee plantation tours",
    "museum visits",
    "art gallery tours",
    "historical site visits",
    "heritage walks",
    "temple visits",
    "cultural performances",
    "photography tours",
    "city sightseeing",
    "guided city tours",
    "architecture tours",
    "river cruises",
    "wildlife safaris",
    "bird watching",
    "national park visits",
    "camping",
    "glamping",
    "stargazing",
    "hiking",
    "trekking",
    "mountain climbing",
    "rock climbing",
    "zip lining",
    "bungee jumping",
    "paragliding",
    "skiing",
    "snowboarding",
    "river rafting",
    "kayaking",
    "canoeing",
    "cycling tours",
    "motorbike tours",
    "off-road adventures",
    "desert safaris",
    "camel rides",
    "hot air balloon rides",
    "theme park visits",
    "spa retreats",
    "yoga retreats",
    "wellness programs",
    "meditation retreats",
    "honeymoon experiences",
    "family entertainment",
    "aquarium visits",
    "zoo visits",
    "festival experiences",
    "concerts and live music",
    "food festivals",
    "farm stays",
    "eco-tourism experiences",
    "volunteer tourism",
    "fishing trips",
    "cruise vacations",
    "train journeys"
]

travel_styles = [
    "luxury",
    "budget",
    "adventure",
    "family",
    "romantic",
    "solo",
    "business",
    "wellness",
    "cultural",
    "eco-tourism"
]


records = []

for _ in range(5000):
    destination, country, dest_type = random.choice(destinations)

    record = {
        "destination_name": destination,
        "country": country,
        "destination_type": dest_type,
        "travel_style": random.choice(travel_styles),
        "budget_min": random.randint(20000, 100000),
        "budget_max": random.randint(100001, 300000),
        "trip_duration": f"{random.randint(3,10)}-{random.randint(11,15)} days",
        "activities": random.sample(activities_pool, 3),
        "meal_preference": random.choice([
               "vegetarian-friendly",
                "vegan-friendly",
                "non-vegetarian-friendly",
                "jain-friendly",
                "mixed"
        ]),
        "description": f"{destination} is a wonderful {dest_type} destination in {country}."
    }

    records.append(record)

with open("travel_data.json", "w") as f:
    json.dump(records, f, indent=2)